comment:
  layout: "diff,flags,files"

coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

flags:
  general:
    paths:
      - (?!(?:handlers|models|plugins|tasks)\/)
  handlers:
    paths:
      - handlers/
  models:
    paths:
      - models/
  plugins:
    paths:
      - plugins/
  tasks:
    paths:
      - tasks/
