name: main

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9
    - name: Cache Poetry virtualenv
      id: virtualenv-cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-
    - name: Install Poetry
      run: |
        curl -fsS https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - -y
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Check import order
      run: make isort_check
    - name: Check formatting using black
      run: make black_check
    - name: Check docstrings with darglint
      run: make darglint
    - name: Test with mypy
      run: make mypy
    - name: Test with pylint
      run: make pylint
    - name: Test with pytest
      run: make pytest
    - name: Upload coverage to Codecov (general)
      uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
      with:
        files: ./coverage.xml
        flags: general
        fail_ci_if_error: true
    - name: Upload coverage to Codecov (handlers)
      uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
      with:
        files: ./coverage-handlers.xml
        flags: handlers
        fail_ci_if_error: true
    - name: Upload coverage to Codecov (models)
      uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
      with:
        files: ./coverage-models.xml
        flags: models
        fail_ci_if_error: true
    - name: Upload coverage to Codecov (plugins)
      uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
      with:
        files: ./coverage-plugins.xml
        flags: plugins
        fail_ci_if_error: true
    - name: Upload coverage to Codecov (tasks)
      uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
      with:
        files: ./coverage-tasks.xml
        flags: tasks
        fail_ci_if_error: true
